databases:
  - name: inmueblesdb
    plan: free
    databaseName: inmuebles
    user: postgres

services:
  - type: web
    plan: free
    name: inmobiliaria
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "python -m gunicorn inmobiliaria.asgi:application -k uvicorn.workers.UvicornWorker"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: inmueblesdb
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4